# Generated by Django 3.1.7 on 2021-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210301_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
